NETWORK_MAPPING = {
    "1C": "earthscope",
    "AZ": "scedc",
    "CI": "scedc",
    "BK": "ncedc",
    "CC": "ncedc",
    "CE": "ncedc",
    "GM": "ncedc",
    "GS": "ncedc",
    "NC": "ncedc",
    "NN": "ncedc",
    "NP": "ncedc",
    "PB": "ncedc",
    "PG": "ncedc",
    "RE": "ncedc",
    "SB": "ncedc",
    "SF": "ncedc",
    "TA": "earthscope",
    "UO": "ncedc",
    "US": "ncedc",
    "UW": "ncedc",
    "WR": "ncedc",
}
